version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mydb


  mongo-express:
      image: mongo-express
      container_name: mongo-express
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
        - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
        - ME_CONFIG_BASICAUTH_USERNAME=mongo
        - ME_CONFIG_BASICAUTH_PASSWORD=mongo

        - ME_CONFIG_MONGODB_URL="mongodb://mongo:mongo@kubernetes.docker.internal:27017"
      depends_on:
        - mongodb
      ports:
        - "8081:8081"