version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "27017:27017"

  mongo-express:
      image: mongo-express:latest
      container_name: mongo-express
      restart: always
      environment:
        ME_CONFIG_MONGO_ADMINUSERNAME: admin_user
        ME_CONFIG_MONGO_ADMINPASSWORD: admin_pass
        ME_CONFIG_MONGODB_URL: mongodb://admin_user:admin_pass@mongodb:27017/
      depends_on:
        - mongodb
      ports:
        - "8081:8081"